export const siteConfig = {
	name: "Melbourne PDS",
	shortName: "MPDS",
	title: "Melbourne Plumbing & Drainage Solutions | 24/7 Emergency Plumber",
	description:
		"24/7 emergency plumbing in Melbourne. Blocked drains, burst pipes, hot water systems, and urgent repairs. Licensed & insured. Call 0431 234 185 for same-day response.",
	url: "https://melbournepds.opeds.app",
	phone: "0431 234 185",
	phoneRaw: "+61431234185",
	email: "melbournepds@gmail.com",
	address: {
		locality: "Melbourne",
		region: "VIC",
		country: "AU",
		postalCode: "3000",
	},
	geo: {
		lat: -37.8136,
		lng: 144.9631,
	},
	keywords: [
		"plumber Melbourne",
		"emergency plumber Melbourne",
		"24/7 plumber Melbourne",
		"blocked drains Melbourne",
		"burst pipes Melbourne",
		"hot water systems Melbourne",
		"drain cleaning Melbourne",
		"licensed plumber Melbourne",
		"same day plumber Melbourne",
		"plumbing services Melbourne",
		"emergency plumbing Melbourne",
		"local plumber Melbourne",
	],
	socialLinks: {
		facebook: "https://www.facebook.com/melbournepds",
	},
	openingHours: "Mo-Su 00:00-24:00",
	priceRange: "$$",
};
